In [1]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4.7], dtype=int)

boyut = arr.shape
eleman_sayisi = arr.size

print(f"Array boyutu: {boyut}")
print(f"Arraydeki eleman sayısı: {eleman_sayisi}")


Array boyutu: (4,)
Arraydeki eleman sayısı: 4


In [11]:
import numpy as np

# 2x3 boyutunda bir array oluşturma
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# 2x2x3 boyutunda bir array oluşturma
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", array_3d)

print("2D Array Boyut:", array_2d.shape)
print("2D Array Eleman Sayısı:", array_2d.size)

print("3D Array Boyut:", array_3d.shape)
print("3D Array Eleman Sayısı:", array_3d.size)

# 2D array'den bir eleman seçme
print("2D Array [0, 1]:", array_2d[0, 1])

# 3D array'den bir eleman seçme
print("3D Array [1, 0, 2]:", array_3d[1, 0, 2])

# 2D array'den bir dilim seçme
print("2D Array Dilim [0, :]:", array_2d[0, :])

# 3D array'den bir dilim seçme
print("3D Array Dilim [1, :, :]:", array_3d[1, :, :])


2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2D Array Boyut: (2, 3)
2D Array Eleman Sayısı: 6
3D Array Boyut: (2, 2, 3)
3D Array Eleman Sayısı: 12
2D Array [0, 1]: 2
3D Array [1, 0, 2]: 9
2D Array Dilim [0, :]: [1 2 3]
3D Array Dilim [1, :, :]: [[ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np

# 1 boyutlu array oluşturma
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# 2x3 boyutunda bir array oluşturma
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# 2x2x3 boyutunda bir array oluşturma
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", array_3d)


# 1D array'den bir eleman seçme
print("1D Array [2]:", array_1d[2])

# 2D array'den bir eleman seçme
print("2D Array [0, 1]:", array_2d[0, 1])

# 3D array'den bir eleman seçme
print("3D Array [1, 0, 2]:", array_3d[1, 0, 2])

# 1D array'den bir dilim seçme
print("1D Array Dilim [1:4]:", array_1d[1:4])

# 2D array'den bir dilim seçme
print("2D Array Dilim [0, :]:", array_2d[0, :])

# 3D array'den bir dilim seçme
print("3D Array Dilim [1, :, :]:", array_3d[1, :, :])


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1D Array [2]: 3
2D Array [0, 1]: 2
3D Array [1, 0, 2]: 9
1D Array Dilim [1:4]: [2 3 4]
2D Array Dilim [0, :]: [1 2 3]
3D Array Dilim [1, :, :]: [[ 7  8  9]
 [10 11 12]]


In [14]:
import numpy as np

# 2x3 boyutunda sıfırlardan oluşan array
zeros_array = np.zeros((2, 3))
print("Sıfırlardan Oluşan Array:\n", zeros_array)

# 2x3 boyutunda birlerden oluşan array
ones_array = np.ones((2, 3))
print("Birlerden Oluşan Array:\n", ones_array)

# Satır bazında birleştirme 
vertical_stack = np.vstack((zeros_array, ones_array))
print("Satır Bazında Birleştirilmiş Array:\n", vertical_stack)

# Sütun bazında birleştirme 
horizontal_stack = np.hstack((zeros_array, ones_array))
print("Sütun Bazında Birleştirilmiş Array:\n", horizontal_stack)


Sıfırlardan Oluşan Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Birlerden Oluşan Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Satır Bazında Birleştirilmiş Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
Sütun Bazında Birleştirilmiş Array:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
