In [1]:
import numpy as np

In [10]:
#Sayılardan oluşan bir boyutlu array oluşturulur. 
# Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. 
# Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakın

sayilar=np.array([1,2,3,4], dtype=int)

print(sayilar.size)
print(sayilar.ndim)


4
1


In [21]:
 #İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı,
#satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve
#dilimleme(slicing) işlemi yapılır. 

sayilar2=np.array([[1,2,3,4],[5,6,7,8]])
sayilar3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Eleman sayısı: ",sayilar2.size)
print("Boyutu: ",sayilar2.ndim)
print("Satır Sayısı:", sayilar2.shape[0])
print("Sütun Sayısı:", sayilar2.shape[1])

print("Eleman sayısı: ",sayilar3.size)
print("Boyutu: ",sayilar3.ndim)
print("Satır Sayısı:", sayilar3.shape[0])
print("Sütun Sayısı:", sayilar3.shape[1])

#2. satırdaki 3. elemana ulaşma
sayilar2[1,3]

#3. satırdaki 3.elemana ulaşma
sayilar3[2,2]

#6, 7 ve 8'i ekrana yazdırma
sayilar2[1:4,1:8]

#9, 10, 11 ve 12'yi ekrana yazdırma
sayilar3[2:6]

Eleman sayısı:  8
Boyutu:  2
Satır Sayısı: 2
Sütun Sayısı: 4
Eleman sayısı:  12
Boyutu:  2
Satır Sayısı: 3
Sütun Sayısı: 4


array([[ 9, 10, 11, 12]])

In [25]:
 #Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. 
#Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

print("1D Array:")
print(array_1d)

# Indexleme
print("İlk eleman:", array_1d[0])
print("Son eleman:", array_1d[-1])

# Dilimleme
print("İlk üç eleman:", array_1d[:3])
print("Son iki eleman:", array_1d[-2:])

print("2D Array:")
print(array_2d)

# Indexleme
print("İlk satır, ikinci sütun elemanı:", array_2d[0, 1])

# Dilimleme
print("İlk satır:", array_2d[0, :])
print("İkinci sütun:", array_2d[:, 1])

print("3D Array:")
print(array_3d)

# Indexleme
print("İlk katman, ikinci satır, üçüncü sütun elemanı:", array_3d[0, 1])

# Dilimleme
print("İlk katman:")
print(array_3d[0, :])
print("İkinci katmanın ilk satırı:")
print(array_3d[1,  :])

1D Array:
[1 2 3 4 5]
İlk eleman: 1
Son eleman: 5
İlk üç eleman: [1 2 3]
Son iki eleman: [4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
İlk satır, ikinci sütun elemanı: 2
İlk satır: [1 2 3]
İkinci sütun: [2 5]
3D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
İlk katman, ikinci satır, üçüncü sütun elemanı: 2
İlk katman:
[1 2 3]
İkinci katmanın ilk satırı:
[4 5 6]


In [28]:
#Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. 
#Bu arrayler satır ve sütun bazında birleştirilir. 
zeros= np.zeros((2,3))
ones= np.ones((2,3))

birlestirme= np.concatenate([zeros,ones])
print(birlestirme)


[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
